### ISSUE TITLE
No ah_token or ah_token_presumed in cookies after logging in

### ISSUE THREAD

**Issue by cvwillegen** [frejonb/mijnah#2]
After logging in to ah.nl web site, the cookies don't contain a ``ah_token`` or ``ah_token_presumed``, so it's not possible to use this library to connect to the Albert Heijn interface any more...

**Comment by frejonb** [comment]
That's unfortunately what happens when relying on APIs that are not provided as a service. Do you know if there's a similar token anymore? I could try to update the library to work with the latest version.

**Comment by frejonb** [comment]
After looking a bit, it seems they are now using a completely different API (GraphQL) and behind Akamai protection. I couldn't quickly figure out how to access the API programmatic. I keep receiving:
```
You don't have permission to access "http://www.ah.nl/gql" on this server.<P>
Reference #18.56b31402.1717439959.5c7df4ea
<P>https://errors.edgesuite.net/18.56b31402.1717439959.5c7df4ea</P>
```

I'm then marking the repo as read-only and will add a notice about it. Feel free to comment if you ever find a solution.
